Divide ph 1
sdsen/opened_extraction pull request #30
Opened 2022-12-09 16:23 UTC by sdsen

fixes #15.

2022-12-09 18:32 UTC, palanik1 commented
@sdsen can you pull in the latest from the main branch and raise the PR

2022-12-09 18:35 UTC, sdsen commented
done

2022-12-09 18:55 UTC, palanik1 requested changes

2022-12-09 18:55 UTC, palanik1 commented on extraction_runner.py
> +    files = []
may be make files an input parameter?

2022-12-09 18:55 UTC, palanik1 commented on foundation_maker.py
> +
can you rename file to something like annotator.py or something  more relevant..

2022-12-10 04:11 UTC, sdsen commented on extraction_runner.py
> +    files = []
these are internal files ... in the sense, that user of the extractor doesn't need to be aware of them. So don't want to specify them as input. If you want to not have them hardcoded, we can move them to a config.json (in a future fix)?

2022-12-10 04:18 UTC, sdsen commented on foundation_maker.py
> +
fixed.

2022-12-10 11:23 UTC, palanik1 commented on extraction_runner.py
> +    files = []
files is being set to empty and then iterated below no?

2022-12-10 11:28 UTC, sdsen commented on extraction_runner.py
> +    files = []
Yes .. all internal  files  based processing now moved to annotater.py . I can remove the function as well and resurface once we need internal files for processing. 

Shall I do that?

2022-12-10 11:29 UTC, palanik1 commented on extraction_runner.py
> +    files = []
Yep..

2022-12-10 11:37 UTC, sdsen commented on extraction_runner.py
> +    files = []
fixed.

2022-12-10 12:02 UTC, merged