add bpf-filter comments
sdsen/opened_extraction pull request #72
Opened 2023-02-23 11:26 UTC by dushyantbehl

2023-02-23 14:29 UTC, sdsen requested changes

2023-02-23 14:29 UTC, sdsen commented on op/bpf-filter-master/commented_bpf-filter-master/drop.c
> +      "description": "This function compares mac addresses represented by two unsigned char arrays of length 6 mac1 and mac2 passed as arguments, returns 1 if true else false",
@dushyantbehl  maybe reword to Returns 1 if they are same, 0 otherwise ?

2023-02-23 14:29 UTC, sdsen commented on op/bpf-filter-master/commented_bpf-filter-master/drop.c
> +      "description": "This function is a filter to be attached on the root interface of a pod's veth pair at TC layer. It takes in a packet in sk_buff form and performs a MAC and IP filter on top. It
Can you specify if all or any of the filters need to match.

2023-02-27 06:48 UTC, dushyantbehl commented
@sdsen updated...you can check again

2023-02-27 06:48 UTC, dushyantbehl commented on op/bpf-filter-master/commented_bpf-filter-master/drop.c
> +      "description": "This function is a filter to be attached on the root interface of a pod's veth pair at TC layer. It takes in a packet in sk_buff form and performs a MAC and IP filter on top. It
Fixed.

2023-02-27 06:48 UTC, dushyantbehl commented on op/bpf-filter-master/commented_bpf-filter-master/drop.c
> +      "description": "This function compares mac addresses represented by two unsigned char arrays of length 6 mac1 and mac2 passed as arguments, returns 1 if true else false",
Fixed.

2023-02-27 06:52 UTC, sdsen approved these changes
lgtm

2023-02-27 06:52 UTC, merged